#!/bin/bash
#
# @todo Nach jedem Skript Fehler abfangen
#
#

set -e

ERROR=1

# Check if we can use colours in our output
use_colour=0
[ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null && use_colour=1

# Some useful functions
progress() {
	[ $use_colour -eq 1 ] && echo -ne "\033[01;32m"
	echo -e "$@" >&2
	[ $use_colour -eq 1 ] && echo -ne "\033[00m"
}

info() {
	[ $use_colour -eq 1 ] && echo -ne "\033[01;34m"
	echo -e "$@" >&2
	[ $use_colour -eq 1 ] && echo -ne "\033[00m"
}

die () {
	[ $use_colour -eq 1 ] && echo -ne "\033[01;31m"
	echo -e "$@" >&2
	[ $use_colour -eq 1 ] && echo -ne "\033[00m"
	exit 1
}

[ "x$(id -un)" == "xroot" ] || die "Sorry, this script must be run as root."

# Creating needed folders
mkdir -p /var/log/yahm
mkdir -p /var/lib/yahm

IS_VERBOSE=0

progress "Install dependencies"
pacman -Syy > /dev/null
pacman --noconfirm --needed -S base-devel wget dos2unix lzo python2 python2-pip git lxc bridge-utils patch gzip openssl dtc linux-raspberrypi-headers dnsmasq> /dev/null
pip2 install python-lzo > /dev/null
info "\t...done"

progress "Ensure python2 is used in /opt/YAHM"
cp share/tools/python/python /usr/local/bin/python
chmod +x /usr/local/bin/python
info "\t...done"

progress "Clean up YAHM directory (removing old versions).."
rm -rf /opt/YAHM
info "\t...done"

# checkout all files
progress "Downloading actual version from git repository.."
mkdir -p /opt
cd /opt

#####################################
#### REMOVE --branch IN MASTER !!!!!#
#####################################
git clone --recursive https://github.com/Myst3rion09/YAHM.git 2>>/var/log/yahm/git.log >>/var/log/yahm/git.log
cd /opt/YAHM
# update modules
git submodule foreach git pull origin master 2>>/var/log/yahm/git.log >>/var/log/yahm/git.log
# update second level submodule
git submodule foreach git submodule update --init --recursive 2>>/var/log/yahm/git.log >>/var/log/yahm/git.log
info "\t..done"

progress "Including YAHM into PATH.."
chmod +x /opt/YAHM/bin/*
ln -sf /opt/YAHM/bin/* /usr/sbin/
info "\t..done"

info "Create LXC container"
/opt/YAHM/bin/yahm-lxc install
info "\t...done"

info "Install piVCCU module"
/opt/YAHM/bin/yahm-module -m pivccu-driver enable
info "\t...done"

info "Create network bridge"
if [ $(cat /etc/default/lxc | grep "USE_LXC_BRIDGE=\"false\"" | wc -l) -eq 0 ]
then
    sed -i /etc/default/lxc -e "s/USE_LXC_BRIDGE=\"false\"/USE_LXC_BRIDGE=\"true\"/"
fi

systemctl enable lxc-net.service
systemctl start lxc-net.service

/opt/YAHM/bin/yahm-network -b lxcbr0 attach_bridge
info "\t...done"

# Info
info "Container is created, please use 'yahm-ctl -n yahm start' to start and 'yahm-ctl -n yahm join' for console access
ERROR=0
